[build]
    base = "flutter_app"
    command = "flutter build web"
    publish = "build/web"

[build.environment]
    FLUTTER_VERSION = "3.32.5"
    NODE_VERSION = "18"

[[plugins]]
    package = "netlify-plugin-flutter"
