name: flutter_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5
  dio: ^5.4.0
  shared_preferences: ^2.2.2
  get_it: ^7.6.9
  curved_navigation_bar: ^1.0.3
  intl: ^0.20.2
  flutter_staggered_animations: ^1.1.1
  cached_network_image: ^3.3.0
  animations: ^2.0.8
  table_calendar: ^3.0.9
  connectivity_plus: ^6.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  dartz: ^0.10.1
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/logo.png
    - assets/images/avatars/
    - assets/images/avatars/parent/
    - assets/images/avatars/child/
    - assets/images/avatars/family/

  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Poppins-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700
  #   - family: ComicSans
  #     fonts:
  #       - asset: assets/fonts/ComicSans-Regular.ttf
  #       - asset: assets/fonts/ComicSans-Bold.ttf
  #         weight: 700
